defmodule Waveform.Synth.Def.Ugens.Chaotic do
  @ugens %{
    ArneodoCoulletTresser: %{},
    Breakcore: %{},
    Brusselator: %{},
    ChaosGen: %{},
    CuspL: %{},
    CuspN: %{},
    DNoiseRing: %{},
    DoubleWell: %{},
    DoubleWell2: %{},
    DoubleWell3: %{},
    FBSineC: %{},
    FBSineL: %{},
    FBSineN: %{},
    FincoSprottL: %{},
    FincoSprottM: %{},
    FincoSprottS: %{},
    FitzHughNagumo: %{},
    GbmanL: %{},
    GbmanN: %{},
    GravityGrid: %{},
    GravityGrid2: %{},
    HenonC: %{},
    HenonL: %{},
    HenonN: %{},
    LatoocarfianC: %{},
    LatoocarfianL: %{},
    LatoocarfianN: %{},
    LinCongC: %{},
    LinCongL: %{},
    LinCongN: %{},
    Logistic: %{},
    LorenzL: %{},
    LotkaVolterra: %{},
    MCLDChaosGen: %{},
    Oregonator: %{},
    Perlin3: %{},
    QuadC: %{},
    QuadL: %{},
    QuadN: %{},
    RMAFoodChainL: %{},
    RosslerL: %{},
    RosslerResL: %{},
    SinOscFB: %{},
    SpruceBudworm: %{},
    StandardL: %{},
    StandardN: %{},
    TermanWang: %{},
    WeaklyNonlinear: %{},
    WeaklyNonlinear2: %{}
  }

  def definitions do
    @ugens
  end
end
