defmodule Waveform.Synth.Def.Ugens.Filters do
  @ugens %{
    Allpass1: %{},
    Allpass2: %{},
    BMoog: %{},
    CrossoverDistortion: %{},
    DFM1: %{},
    Decimator: %{},
    DiodeRingMod: %{},
    Disintegrator: %{},
    Filter: %{},
    Friction: %{},
    Gammatone: %{},
    Goertzel: %{},
    HairCell: %{},
    IIRFilter: %{},
    InsideOut: %{},
    LTI: %{},
    Lag2UD: %{},
    Lag3UD: %{},
    LagUD: %{},
    MeanTriggered: %{},
    Meddis: %{},
    MedianTriggered: %{},
    MoogFF: %{},
    MoogLadder: %{},
    MoogVCF: %{},
    NL: %{},
    NL2: %{},
    NLFiltC: %{},
    NLFiltL: %{},
    NLFiltN: %{},
    RLPFD: %{},
    RMEQ: %{},
    RMEQSuite: %{},
    RMShelf: %{},
    RMShelf2: %{},
    RegaliaMitraEQ: %{},
    SVF: %{},
    SineShaper: %{},
    SmoothDecimator: %{},
    Streson: %{},
    BAllPass: %{},
    BBandPass: %{},
    BBandStop: %{},
    BEQSuite: %{},
    BHiPass: %{},
    BHiPass4: %{},
    BHiShelf: %{},
    BLowPass: %{},
    BLowPass4: %{},
    BLowShelf: %{},
    BPeakEQ: %{},
  }

  def definitions do
    @ugens
  end
end
